
GET http://localhost:5202/users HTTP/1.1
###

GET http://localhost:5202/users/648b10cbbe7cc37503820eab HTTP/1.1    
###

POST http://localhost:5202/users HTTP/1.1
Content-Type: application/json

{
    "name":"Kabouter Lui",
    "service": 0,
    "status": "Active"
}
###

PUT http://localhost:5202/users/648b11dabe7cc37503820eb1 HTTP/1.1
Content-Type: application/json

# {
#     "name":"Bram",
#     "service": 1,
#     "status": "Active"
# }

{
    "service": 2
}

###

POST http://localhost:5202/activity HTTP/1.1
Content-Type: application/json

{
    "userId": "648b10cbbe7cc37503820eab",
    "movement": "left arm raised"
}
###

GET http://localhost:5202/activity/648b10cbbe7cc37503820eab HTTP/1.1
###

GET http://localhost:5202/activity/latest/648b10cbbe7cc37503820eab HTTP/1.1
###